"""initial

Revision ID: 168f2930926c
Revises: 
Create Date: 2022-09-02 03:06:37.626580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '168f2930926c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('birthdate', sa.DATE(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('leader_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['leaders.id'], name='FK_member_id_leader_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('leaders')
    # ### end Alembic commands ###
