version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    depends_on:
      - api
    ports:
      - "3000:3000"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

  db:
    build:
      context: ./api/app/db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
      POSTGRES_DB: application